name: tests.yml
on: 
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs: 
    run-pytest:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with: 
                python-version: 3.8
            - name: Installing dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pytest
                pip install -r requirements_dev.txt
            - name: Running tests
              run: |
                  pytest -v -s
            - name: Run Linter
              run: |
                  pylint *.py
